### ISSUE TITLE
Can you make it javascript version? Many people need it

### ISSUE THREAD

**Issue by hoogw** [simonw/geojson-to-sqlite#14]
I have sqlite file db running on browser with js. 

I need this tool to convert user uploaded, or from URL geojson to sqlite file (in user browser)

How to do that? 

if you can make a node version of it, we can browserify it and import it into browser javascript environment.

**Comment by simonw** [comment]
That's definitely out of scope for this project. If you want to build something like that you may find https://github.com/kripken/sql.js/ useful.

**Comment by hoogw** [comment]
yes, this is want I need. 

https://github.com/sql-js/sql.js
