### ISSUE TITLE
Also support KML?

### ISSUE THREAD

**Issue by psychemedia** [simonw/geojson-to-sqlite#9]
Would it also be useful to support additional geodata types, eg KML?

I've used `kml2geojson` in the past to convert KML to the more convenient geojson format, although it probably has dependencies on an XML parser that would add weight to this package.

**Comment by simonw** [comment]
Given the existence of `shapefile-to-sqlite` and this tool I think `kml-to-SQLite` as a separate tool would be the way to solve this.
